# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class Receipt(BaseModel):
    isValidReceipt: typing.Optional[bool] = Field(default=None, description='Whether this image is a valid receipt. Set to true only if the image clearly shows a receipt, invoice, or similar purchase document. Set to false for non-receipt images like photos, screenshots, memes, documents, etc.')
    validationError: typing.Optional[str] = Field(default=None, description='If isValidReceipt is false, provide a brief explanation of why this is not a valid receipt (e.g., \'Image shows a landscape photo, not a receipt\'). If isValidReceipt is true, this should be an empty string.')
    id: typing.Optional[str] = Field(default=None, description='For internal reference and programmatic use, would not go into V1 output table.')
    amount: typing.Optional[float] = Field(default=None, description='The total amount of the receipt. Include all tips, taxes, etc. in the amount. If you cannot determine the amount, just put zero.')
    date: typing.Optional[str] = Field(default=None, description='The date of the receipt. Format should be MM/DD/YYYY. If you cannot determine the date, just put an empty string.')
    vendor: typing.Optional[str] = Field(default=None, description='The vendor of the receipt. If you cannot determine the vendor, just put an empty string.')
    category: typing.List[types.ReceiptCategory] = Field(description='The canonical categories for the receipt. Use only values from ReceiptCategory. If multiple categories are present, list them all. If you can\'t determine a category, present an empty list.')
    paymentMethod: typing.List[str] = Field(description='The method of payment used for the receipt. Examples could include: Cash, Card, Check, Gift Card, etc. If multiple payment methods are present, list them all. In the rare case when you can\'t determine a payment method, just present an empty list.')
    excludeFromTable: typing.Optional[bool] = Field(default=None, description='Whether to exclude this receipt from the output table. Default is false. Should only be true if the receipt meets the exclusion conditions described in input documents.')
    exclusionReason: typing.Optional[str] = Field(default=None, description='If excludeFromTable is true, provide a brief explanation of why this receipt was excluded. If excludeFromTable is false, this should be an empty string.')

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
