# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class Receipt(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='For internal reference and programmatic use, would not go into V1 output table.')
    amount: typing.Optional[float] = Field(default=None, description='The total amount of the receipt. Include all tips, taxes, etc. in the amount.')
    date: typing.Optional[str] = Field(default=None, description='The date of the receipt. Format should be MM/DD/YYYY.')
    vendor: typing.Optional[str] = Field(default=None, description='The vendor of the receipt.')
    category: typing.List[str] = Field(description='The category of the receipt. Examples could include: Food/restaurants, Clothing, Entertainment, Housing, etc. If multiple categories are present, list them all. In the rare case when you can\'t determine a category, just present an empty list.')
    paymentMethod: typing.List[str] = Field(description='The method of payment used for the receipt. Examples could include: Cash, Card, Check, Gift Card, etc. If multiple payment methods are present, list them all. In the rare case when you can\'t determine a payment method, just present an empty list.')

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
