# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (2)
# #########################################################################

class Receipt(BaseModel):
    id: str = Field(description='For internal reference and programmatic use, would not go into V1 output table.')
    amount: float = Field(description='The total amount of the receipt. Include all tips, taxes, etc. in the amount.')
    date: str = Field(description='The date of the receipt. Format should be MM/DD/YYYY.')
    vendor: str = Field(description='The vendor of the receipt.')
    category: typing.List[str] = Field(description='The category of the receipt. Examples could include: Food/restaurants, Clothing, Entertainment, Housing, etc. If multiple categories are present, list them all. In the rare case when you can\'t determine a category, just present an empty list.')
    paymentMethod: typing.List[str] = Field(description='The method of payment used for the receipt. Examples could include: Cash, Card, Check, Gift Card, etc. If multiple payment methods are present, list them all. In the rare case when you can\'t determine a payment method, just present an empty list.')

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
